### ISSUE TITLE
服务器无法访问

### ISSUE THREAD

**Issue by XiaotianDong** [xiao201261/safetree_web#13]
最近发现Demo的服务器访问超时了

**Comment by xiao201261** [comment]
你这边网络问题？ 
我这是正常的 
<img width="485" alt="image" src="https://user-images.githubusercontent.com/6511667/90115357-8da55400-dd86-11ea-8fa6-fac076362572.png">

**Comment by XiaotianDong** [comment]
我挂着梯子勉强能上吧，你服务器可能被墙了？？？？？
![image](https://user-images.githubusercontent.com/34956162/90132067-b84fd680-dd9f-11ea-92d4-a179a811ae1a.png)

**Comment by xiao201261** [comment]
部分地区吧，可能没什么办法了

**Comment by XiaotianDong** [comment]
嗯，不确定以后能不能好了
