### ISSUE TITLE
教育平台的api Google有缓存过2019-8的

### ISSUE THREAD

**Issue by XiaotianDong** [xiao201261/safetree_web#4]

**Comment by xiao201261** [comment]
现在好像也是能访问的？
[api](https://119.safetree.com.cn/Help)

然后我自己写的做题全部是调用网页版来完成的，只有手机登录用了客户端api（

以及 我已经给你发邮件了，outlook经常会把邮件扔垃圾箱，检查下么？

**Comment by XiaotianDong** [comment]
现在可能改了，新的是appapi.safetree.com,但这个还能用
