### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by XiaotianDong** [xiao201261/safetree_web#5]
能不能给一下教师端登陆、查找并重置学生密码的API？

**Comment by xiao201261** [comment]
教师端登录和学生端的一样。
`https://' + city + '.xueanquan.com/EduAdmin/ClassManagement/StudentPassWordReset?studentid=' + studentid`
重置密码是这样的 需要获取学生的id

学生列表
`https://' + city + '.xueanquan.com/EduAdmin/ClassManagement/ClassManagement'`

**Comment by XiaotianDong** [comment]
这个API是用的GET还是POST？，如果是POST，它的body里都有什么？，然后请求头你是怎么写的？？

________________________________
dongxiaotian123456@outlook.com
